yo volume create: fix bogus error
A simple "volume create NAME SIZE" results in:

    error: --attach requires a value for --for

But "--attach" was not specified. This is because "setup" defaults to
true (to help in the iscsi case), and for some reason this triggers
automatically setting "attach" to true.

I believe that at one point, "--setup" was non-default behavior and so
it made sense that if the user explicitly requested it, then we would
expect an attachment as well. But now that it's default and we have
--no-setup, this is a bad check and should be deleted.

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>